/* Four Square API */

const CLIENT_ID = "GF0BARDSETANEVFHIYDR12KQBR4SU2CHLGNVRRBJVAHYMNIQ";
const CLIENT_SECRET = "REYNVNPRY3R3OOVZLDVBNQUEADXOM2KKTDVGTBA2YRWN2AOC";
const API = "https://api.foursquare.com/v2";
const VERSION = "20180725";

const RADIUS_M = 250;
const SEARCH_RESULTS = 1;
